"""Add embedding metadata to content chunks

Revision ID: 1ab4a471156a
Revises: 4248d36f19f5
Create Date: 2026-09-19 20:22:33.603329

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1ab4a471156a'
down_revision = '4248d36f19f5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('content_chunks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('embedding_model', sa.String(length=150), nullable=True))
        batch_op.add_column(sa.Column('embedding_dimensions', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('embedded_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('content_chunks', schema=None) as batch_op:
        batch_op.drop_column('embedded_at')
        batch_op.drop_column('embedding_dimensions')
        batch_op.drop_column('embedding_model')

    # ### end Alembic commands ###
