"""Add maximum worksheet attempts

Revision ID: 99316b4ace03
Revises: 5cb063275f0d
Create Date: 2026-09-22 16:56:23.391757

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '99316b4ace03'
down_revision = '5cb063275f0d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('worksheets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('max_attempts', sa.Integer(), server_default='3', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('worksheets', schema=None) as batch_op:
        batch_op.drop_column('max_attempts')

    # ### end Alembic commands ###
